### ISSUE TITLE
iOS 8 bubble size issue - deprecation

### ISSUE THREAD

**Issue by alessign** [SkyTrix/STBubbleTableViewCell#1]
Hi, splendid source, thank you! I am having problems to create size of the bubbles with iOS 8 deprecation:

```
    size = [self.textLabel.text sizeWithFont:self.textLabel.font       constrainedToSize:CGSizeMake(self.frame.size.width - minInset - STBubbleWidthOffset, CGFLOAT_MAX) lineBreakMode:NSLineBreakByWordWrapping];
```

Instead, they're suggesting to use:

```
    NSMutableParagraphStyle *paragraphStyle = [[NSMutableParagraphStyle alloc] init];
    paragraphStyle.lineBreakMode = NSLineBreakByWordWrapping;

    CGRect textRect2 = [self.textLabel.text boundingRectWithSize:CGSizeMake(self.frame.size.width - minInset - STBubbleWidthOffset, CGFLOAT_MAX) options: NSStringDrawingUsesLineFragmentOrigin attributes:@{NSParagraphStyleAttributeName: paragraphStyle.copy} context:nil];
    size = textRect2.size;
    NSLog(@"textRect size 2: %f, %f", size.width, size.height);
```

Which kinda works, but not always. In one line text sometimes correct, sometimes not. In multi line sometimes correct, sometimes not. If you do a lot of text, it shows only first 3 lines....

I tried to fiddle with the formula, but no luck. Can you please suggest the correct way? The old build for iOS 5 works perfectly!

Thank you
Alex

![ios simulator screen shot 18 dec 2014 11 16 33](https://cloud.githubusercontent.com/assets/3117528/5487396/2559c0b4-86a9-11e4-84c4-4c2fda4a2e95.png)

**Comment by alessign** [comment]
I have figured out:

```
   CGRect textRect2 = [self.textLabel.text boundingRectWithSize:CGSizeMake(self.frame.size.width - minInset - STBubbleWidthOffset, CGFLOAT_MAX)
                                                        options:NSStringDrawingUsesLineFragmentOrigin
                                                     attributes:@{NSFontAttributeName:self.textLabel.font}
                                                        context:nil];


    size = textRect2.size;
```

All works perfectly! Thanks again for sharing

**Comment by SkyTrix** [comment]
Sorry for the late reply. I figured it's no use to support anything lower than iOS 7 now so I've changed the deployment target to iOS 7 and replaced the deprecated methods with your implementation. Thanks!

**Comment by AbdulMuksith** [comment]
Hi SkyTrix can you please help with this to edit and select multiple bubbles.
